name: deploy to DigitalOcean instace

on: 
  push:
    branches: [develop]
jobs:
  building:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: install dependencies
        run: npm install
      - name: build project
        run: npm run build
  deploying:
    needs: [building]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: deploy to DigitalOcean instance
        run: cat ./dist/index.html

